[plugin]
name = "spark-shuffle"
description = ""
version = "1.0"
maintainer_name = "SequenceIQ"
maintainer_email = "info@sequenceiq.com"
website_url = "https://github.com/keyki/consul-plugins-spark-shuffle"

[plugin.config]

[plugin.compatibility]
